{{- if .Values.openshift.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "ublhub.fullname" . }}
  labels:
    {{- include "ublhub.labels" . | nindent 4 }}
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: {{ include "ublhub.fullname" . }}
{{- end}}