name: CI

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  linux-jvm-tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [ "standalone", "enterprise" ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.4.0
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - name: Maven
        run: mvn verify $MAVEN_ARGS
        env:
          MAVEN_ARGS: "-P${{ matrix.flavor }}"
      - name: Prepare failure archive (if maven failed)
        if: failure()
        shell: bash
        run: find . -name '*-reports' -type d | tar -czvf test-reports.tgz -T -
      - name: Upload failure archive (if maven failed)
        uses: actions/upload-artifact@v2.2.4
        if: failure()
        with:
          name: test-reports-${{ matrix.flavor }}
          path: 'test-reports.tgz'
